services:
  structurizr:
    image: structurizr/lite:latest
    environment:
      STRUCTURIZR_WORKSPACE_FILENAME: system-landscape
    volumes:
      - ./documentation:/usr/local/structurizr
    ports:
      - "8080:8080"
